Minor: use correct testing.T in tests / teardown (#895)
Tests failed locally when running with docker-compose-local.yaml, with an error like this:
```
buildkite_integ-test-sticky-on_1 exited with code 2
integ-test-sticky-off_1  | --- FAIL: TestIntegrationSuite (139.30s)
integ-test-sticky-off_1  |     --- PASS: TestIntegrationSuite/TestActivityCancelRepro (7.86s)
...
integ-test-sticky-off_1  |     --- PASS: TestIntegrationSuite/TestChildWFWithParentClosePolicyAbandon (5.19s)
        Error Trace:    integration_test.go:3127:
integ-teError:      f_1 Should be true
integ-teTest:       f_1 TestIntegrationSuite
integ-test-sticky-off_1  |     --- FAIL: TestIntegrationSuite/TestChildWFWithParentClosePolicyTerminate (5.16s)
integ-test-sticky-off_1  |         testing.go:820: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

The cause is pretty straightforward: the testing.T in the assertions is owned by the parent, but being used in sub-tests
(like TestChildWFWithParentClosePolicy), which is incorrect, and can lead to the wrong test(s) being blamed.
It'll also lead to logs not being printed for the right test (if used).  So this should be better in pretty much every way.