Un-pin zap, bump to a newer version to pull in zaptest logger (#438)
* Un-pin zap, bump to a newer version to pull in zaptest logger

Mostly motivated by the addition of a testing.T.Logf-compatible logger
provided by zap, which allows quite a lot cleaner test-logs, especially
when they are run in parallel.

But generally: there's no reason for zap to be pinned to a *specific*
version like it was. Ranges are far nicer for users of libraries.

* Remove testify.Suite from backoff tests

While trying to change these >= / < checks to something like
`assert.InDelta`, and generally trying to trigger edge cases, I
found that these tests aren't really sufficient:

```
cadence$ go test -race -count 30 ./internal/common/backoff/
--- FAIL: TestDefaultPublishRetryPolicy (0.00s)
        Error Trace:    retrypolicy_test.go:156
	Error:      	Should be true
	Test:       	TestDefaultPublishRetryPolicy
	Messages:   	NextBackoff too low: actual: 1.035903185s, expected: 1.3s
FAIL
FAIL	go.uber.org/cadence/internal/common/backoff	0.684s
```

If you run the tests enough, you eventually get values that
exceed the 0.8x limit implied by the tests.  I haven't sat down
and run through the math to figure out real bounds, but they're
currently misleading, it'd be good to get that fixed.